services:
  demo:
  wmts:
    restful: true
    restful_template: "/{Layer}/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.{Format}"

layers:
  - name: satellite
    title: Satellite View
    sources: [satellite_cache]

caches:
  satellite_cache:
    grids: [my_grid]
    sources: [esri_source]
    format: image/webp
    request_format: image/jpeg
    cache:
      type: file
      directory: /cache_data

sources:
  esri_source:
    type: tile
    # ArcGIS: z/y/x.
    url: https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/%(z)s/%(y)s/%(x)s
    grid: my_grid
    on_error:
      403: { response: transparent }
      404: { response: transparent }
      500: { response: transparent }
      502: { response: transparent }
      503: { response: transparent }
      504: { response: transparent }
grids:
  my_grid:
    srs: "EPSG:3857"
    origin: nw
    # These numbers ensure that Z14 in the browser = Z14 in ArcGIS
    res:
      [
        156543.03392804097,
        78271.51696402048,
        39135.75848201024,
        19567.87924100512,
        9783.93962050256,
        4891.96981025128,
        2445.98490512564,
        1222.99245256282,
        611.49622628141,
        305.748113140705,
        152.8740565703525,
        76.43702828517625,
        38.21851414258813,
        19.109257071294063,
        9.554628535647032,
        4.777314267823516,
        2.388657133911758,
        1.194328566955879,
        0.5971642834779395,
        0.29858214173896974,
      ]
