server {
    listen 80;
    server_tokens off;

    set $secure_link_secret "<LINK_SECRET>";
    set $secure_link_key "<LINK_KEY>";

    location = /favicon.ico {
        return 301 https://example.dep.ovh/favicon.ico;
    }

    location ^~ /satellite/ {
        secure_link $arg_hash,$arg_expires;
        secure_link_md5 "$arg_expires$uri $secure_link_secret";
        set $access_status "blocked";
        if ($arg_key = $secure_link_key) {
            set $access_status "allowed";
        }
        if ($secure_link = "1") {
            set $access_status "allowed";
        }
        if ($secure_link = "0") {
            set $access_status "expired";
        }
        if ($access_status = "blocked") { return 403; }
        if ($access_status = "expired") { return 410; }

        rewrite ^/satellite/([0-9]+)/([0-9]+)/([0-9]+)\.([a-z]+)$ /wmts/satellite/my_grid/$1/$2/$3.$4 break;
        proxy_pass http://mapproxy:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        secure_link $arg_hash,$arg_expires;
        secure_link_md5 "$arg_expires$uri $secure_link_secret";
        set $access_status "blocked";
        if ($arg_key = $secure_link_key) {
            set $access_status "allowed";
        }
        if ($secure_link = "1") {
            set $access_status "allowed";
        }
        if ($secure_link = "0") {
            set $access_status "expired";
        }
        if ($access_status = "blocked") { return 403; }
        if ($access_status = "expired") { return 410; }

        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";

        proxy_pass http://tileserver:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
